In [13]:
import numpy as np
import math

if __name__ == '__main__':
    #Load data
    binblue = np.load('./data/SampleData/binblue.npy')
    black = np.load('./data/SampleData/black.npy')
    brown = np.load('./data/SampleData/brown.npy')
    green = np.load('./data/SampleData/green.npy')
    grey = np.load('./data/SampleData/grey.npy')
    #otherblue = np.load('./data/SampleData/otherblue.npy')
    purple = np.load('./data/SampleData/purple.npy')
    red = np.load('./data/SampleData/red.npy')
    skyblue = np.load('./data/SampleData/skyblue.npy')
    white = np.load('./data/SampleData/white.npy')
    yellow = np.load('./data/SampleData/yellow.npy')

In [14]:
    #Generate data
    X1 = binblue
    X2 = black
    X3 = brown
    X4 = green
    X5 = grey
    X6 = purple
    X7 = red
    X8 = skyblue
    X9 = white
    X10 = yellow
    y1, y2, y3, y4, y5, y6, y7, y8,y9,y10 = np.full(X1.shape[0],1), np.full(X2.shape[0],2), np.full(X3.shape[0],3), np.full(X4.shape[0],4), np.full(X5.shape[0],5), np.full(X6.shape[0],6), np.full(X7.shape[0],7), np.full(X8.shape[0],8),np.full(X9.shape[0],9),np.full(X10.shape[0],10)
    
    
    #Calculate Gaussian Naive Bayes parameters for each class
   #Calculate mean for each class
    mean_rgb = np.zeros((10,3))
    mean_rgb[0,:] =  np.mean(X1,axis = 0)
    mean_rgb[1,:] =  np.mean(X2,axis = 0)
    mean_rgb[2,:] =  np.mean(X3,axis = 0)
    mean_rgb[3,:] =  np.mean(X4,axis = 0)
    mean_rgb[4,:] =  np.mean(X5,axis = 0)
    mean_rgb[5,:] =  np.mean(X6,axis = 0)
    mean_rgb[6,:] =  np.mean(X7,axis = 0)
    mean_rgb[7,:] =  np.mean(X8,axis = 0)
    mean_rgb[8,:] =  np.mean(X9,axis = 0)
    mean_rgb[9,:] =  np.mean(X10,axis = 0)
    
   

    
   #Calculate variance for each class
    var_rgb = np.zeros((10,3))
    var_rgb[0,:] =  np.var(X1,axis = 0)
    var_rgb[1,:] =  np.var(X2,axis = 0)
    var_rgb[2,:] =  np.var(X3,axis = 0) 
    var_rgb[3,:] =  np.var(X4,axis = 0)
    var_rgb[4,:] =  np.var(X5,axis = 0)
    var_rgb[5,:] =  np.var(X6,axis = 0)
    var_rgb[6,:] =  np.var(X7,axis = 0)
    var_rgb[7,:] =  np.var(X8,axis = 0)
    var_rgb[8,:] =  np.var(X9,axis = 0)
    var_rgb[9,:] =  np.var(X10,axis = 0)
 

  #Calculate mu for each class, mu = mean for each class
    mu = np.zeros((10,3))
    mu = mean_rgb
    
  #Calculate sigma for each class, sigma = n/n-1 * var
    sigma = np.zeros((10,3))
    sigma = var_rgb

In [15]:
   print("mu",mu)
   print("sigma",var_rgb)

mu [[113.91622572 206.50479637 160.97238248]
 [ 95.67741935  52.97616487  60.45967742]
 [ 36.38911829  88.69808113 155.77362157]
 [ 52.30760184 133.73473752 105.19736983]
 [ 67.48803014  15.1526444  172.78927538]
 [132.48281016 155.67115097  81.91479821]
 [145.94249685 193.01765448 208.60857503]
 [104.28818549 109.78918151 224.62268573]
 [111.76906844  25.25324088 230.08260476]
 [ 25.25       130.38509874 246.85682226]]
sigma [[1.41120547e+01 8.77918703e+02 2.12284418e+03]
 [1.40234361e+03 8.18073805e+02 3.42142639e+02]
 [2.67957630e+03 3.17192633e+03 3.61938208e+03]
 [1.37363416e+02 4.34116528e+03 1.08501055e+03]
 [1.94666800e+03 5.83112124e+01 1.29454660e+03]
 [1.78969392e+01 6.92435954e+02 2.05369229e+03]
 [4.34819947e+03 5.56532882e+03 3.49797188e+03]
 [4.78285527e+01 1.79100297e+03 4.18704482e+02]
 [2.78521889e+02 1.71849044e+02 1.19315808e+03]
 [5.20994165e+00 7.83096391e+03 1.25377615e+02]]


In [16]:
    np.save('./mu.npy', mu)
    np.save('./sigma.npy', sigma)