In [8]:
import numpy as np
import math
import cv2
import colorsys
if __name__ == '__main__':
    #Load data
    binblue = np.load('./data/SampleData/binblue.npy')
    black = np.load('./data/SampleData/black.npy')
    brown = np.load('./data/SampleData/brown.npy')
    green = np.load('./data/SampleData/green.npy')
    grey = np.load('./data/SampleData/grey.npy')
    #otherblue = np.load('./data/SampleData/otherblue.npy')
    purple = np.load('./data/SampleData/purple.npy')
    red = np.load('./data/SampleData/red.npy')
    skyblue = np.load('./data/SampleData/skyblue.npy')
    white = np.load('./data/SampleData/white.npy')
    yellow = np.load('./data/SampleData/yellow.npy')

In [17]:
    #Generate data
    X1 = binblue
    X2 = black
    X3 = brown
    X4 = green
    X5 = grey
    X6 = purple
    X7 = red
    X8 = skyblue
    X9 = white
    X10 = yellow
    
    y1, y2, y3, y4, y5, y6, y7, y8,y9,y10 = np.full(X1.shape[0],1), np.full(X2.shape[0],2), np.full(X3.shape[0],3), np.full(X4.shape[0],4), np.full(X5.shape[0],5), np.full(X6.shape[0],6), np.full(X7.shape[0],7), np.full(X8.shape[0],8),np.full(X9.shape[0],9),np.full(X10.shape[0],10)
    X1 = X1.reshape((X1.shape[0],1,3))
    X1 = cv2.cvtColor(X1, cv2.COLOR_HSV2RGB)
    X1 = X1.reshape(X1.shape[0],3)
    
    X2 = X2.reshape((X2.shape[0],1,3))
    X2 = cv2.cvtColor(X2, cv2.COLOR_HSV2RGB)
    X2 = X2.reshape(X2.shape[0],3)
    
    X3 = X3.reshape((X3.shape[0],1,3))
    X3 = cv2.cvtColor(X3, cv2.COLOR_HSV2RGB)
    X3 = X3.reshape(X3.shape[0],3)
    
    X4 = X4.reshape((X4.shape[0],1,3))
    X4 = cv2.cvtColor(X4, cv2.COLOR_HSV2RGB)
    X4 = X4.reshape(X4.shape[0],3)
    
    X5 = X5.reshape((X5.shape[0],1,3))
    X5 = cv2.cvtColor(X5, cv2.COLOR_HSV2RGB)
    X5 = X5.reshape(X5.shape[0],3)
    
    X6 = X6.reshape((X6.shape[0],1,3))
    X6 = cv2.cvtColor(X6, cv2.COLOR_HSV2RGB)
    X6 = X6.reshape(X6.shape[0],3)
    
    X7 = X7.reshape((X7.shape[0],1,3))
    X7 = cv2.cvtColor(X7, cv2.COLOR_HSV2RGB)
    X7 = X7.reshape(X7.shape[0],3)
    
    X8 = X8.reshape((X8.shape[0],1,3))
    X8 = cv2.cvtColor(X8, cv2.COLOR_HSV2RGB)
    X8 = X8.reshape(X8.shape[0],3)
    
    X9 = X9.reshape((X9.shape[0],1,3))
    X9 = cv2.cvtColor(X9, cv2.COLOR_HSV2RGB)
    X9 = X9.reshape(X9.shape[0],3)
    
    X10 = X10.reshape((X10.shape[0],1,3))
    X10 = cv2.cvtColor(X10, cv2.COLOR_HSV2RGB)
    X10 = X10.reshape(X10.shape[0],3)
    

    #Calculate Gaussian Naive Bayes parameters for each class
   #Calculate mean for each class
    mean_rgb = np.zeros((10,3))
    mean_rgb[0,:] =  np.mean(X1,axis = 0)
    mean_rgb[1,:] =  np.mean(X2,axis = 0)
    mean_rgb[2,:] =  np.mean(X3,axis = 0)
    mean_rgb[3,:] =  np.mean(X4,axis = 0)
    mean_rgb[4,:] =  np.mean(X5,axis = 0)
    mean_rgb[5,:] =  np.mean(X6,axis = 0)
    mean_rgb[6,:] =  np.mean(X7,axis = 0)
    mean_rgb[7,:] =  np.mean(X8,axis = 0)
    mean_rgb[8,:] =  np.mean(X9,axis = 0)
    mean_rgb[9,:] =  np.mean(X10,axis = 0)
    
   

    
   #Calculate variance for each class
    var_rgb = np.zeros((10,3))
    var_rgb[0,:] =  np.var(X1,axis = 0)
    var_rgb[1,:] =  np.var(X2,axis = 0)
    var_rgb[2,:] =  np.var(X3,axis = 0) 
    var_rgb[3,:] =  np.var(X4,axis = 0)
    var_rgb[4,:] =  np.var(X5,axis = 0)
    var_rgb[5,:] =  np.var(X6,axis = 0)
    var_rgb[6,:] =  np.var(X7,axis = 0)
    var_rgb[7,:] =  np.var(X8,axis = 0)
    var_rgb[8,:] =  np.var(X9,axis = 0)
    var_rgb[9,:] =  np.var(X10,axis = 0)
 

  #Calculate mu for each class, mu = mean for each class
    mu = np.zeros((10,3))
    mu = mean_rgb
    
  #Calculate sigma for each class, sigma = n/n-1 * var
    sigma = np.zeros((10,3))
    sigma = var_rgb

In [18]:
   print("mu",mu)
   print("sigma",var_rgb)

mu [[ 30.26391971  57.04499368 160.97238248]
 [ 48.92939068  51.59157706  59.53942652]
 [155.38438183 123.92907457  97.66261841]
 [ 72.88196301 105.17448947  53.48455041]
 [166.28677113 168.90483849 168.80356568]
 [ 53.45142003  33.32436472  81.9103139 ]
 [208.60832282  37.22244641  51.4814628 ]
 [128.3990948  174.82152273 224.56906199]
 [208.01447091 218.84775399 230.05456738]
 [246.85682226 227.81732496 123.9564632 ]]
sigma [[ 490.33805471  761.85541591 2122.84418316]
 [ 238.20827597  241.57100432  346.23876813]
 [3693.78581874 2766.24175122 2335.16356011]
 [ 905.01204824 1084.29244448  985.32342751]
 [1077.54065439 1228.35647294 1370.50155049]
 [1513.39263251  815.98297886 2054.10854833]
 [3497.95680337 1991.30890347 1605.39013557]
 [1734.83845301  905.55080054  420.60921568]
 [ 886.76554278 1191.85351696 1196.89090241]
 [ 125.37761504  491.46528333 7805.07305966]]


In [19]:
    np.save('./mu.npy', mu)
    np.save('./sigma.npy', sigma)